[package]
name = "rs_pmm_tools"
version = "0.1.0"
authors = ["philipp <descpl@yahoo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
